-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('ITEM_SOLD', 'ITEM_LIKED', 'BARTER_REQUEST', 'BARTER_ACCEPTED', 'BARTER_REJECTED', 'WTB_RESPONSE', 'PRICE_ALERT', 'DISCUSSION_REPLY', 'SYSTEM_ANNOUNCEMENT', 'DONATION_REQUEST', 'BADGE_EARNED', 'AN_ITEM_POST') NOT NULL;
